
const ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST"
const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS"
const ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL"


const GET_SERVICE_REQUEST = "GET_SERVICE_REQUEST"
const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS"
const GET_SERVICE_FAIL = "GET_SERVICE_FAIL"

const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
const GET_SERVICES_FAIL = "GET_SERVICES_FAIL"

const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST"
const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS"
const UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL"


const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST"
const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS"
const DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL"

export {
    ADD_SERVICE_FAIL,ADD_SERVICE_REQUEST,ADD_SERVICE_SUCCESS,
    GET_SERVICES_FAIL,GET_SERVICES_REQUEST,GET_SERVICES_SUCCESS,
    GET_SERVICE_REQUEST,GET_SERVICE_FAIL,GET_SERVICE_SUCCESS,
    UPDATE_SERVICE_FAIL,UPDATE_SERVICE_REQUEST,UPDATE_SERVICE_SUCCESS,
    DELETE_SERVICE_FAIL,DELETE_SERVICE_REQUEST,DELETE_SERVICE_SUCCESS
}
